import React, { useState, useEffect } from 'react';
import { useTranslation } from '../i18n/useTranslation';
import { useSettingsStore } from '../stores/settingsStore';

interface SettingsPanelProps {
  isOpen: boolean;
  onClose: () => void;
}

export function SettingsPanel({ isOpen, onClose }: SettingsPanelProps) {
  const { t } = useTranslation();
  const {
    skillSettings,
    previewSettings,
    loadSettings,
    setAutoGenerateSkill,
    setTriggerThreshold,
    setPreviewFps,
    isLoading,
  } = useSettingsStore();

  const [localSkillThreshold, setLocalSkillThreshold] = useState(skillSettings.triggerThreshold);
  const [localPreviewFps, setLocalPreviewFps] = useState(previewSettings.fps);

  useEffect(() => {
    if (isOpen) {
      loadSettings();
    }
  }, [isOpen]);

  useEffect(() => {
    setLocalSkillThreshold(skillSettings.triggerThreshold);
    setLocalPreviewFps(previewSettings.fps);
  }, [skillSettings, previewSettings]);

  const handleAutoGenerateChange = async (checked: boolean) => {
    await setAutoGenerateSkill(checked);
  };

  const handleThresholdChange = async () => {
    if (localSkillThreshold !== skillSettings.triggerThreshold && localSkillThreshold >= 1) {
      await setTriggerThreshold(localSkillThreshold);
    }
  };

  const handleFpsChange = async () => {
    if (localPreviewFps !== previewSettings.fps && localPreviewFps >= 1 && localPreviewFps <= 30) {
      await setPreviewFps(localPreviewFps);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70">
      <div className="w-[480px] max-h-[80vh] rounded-lg bg-[var(--color-surface)] p-6 shadow-lg overflow-y-auto">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-lg font-semibold text-[var(--color-text-primary)]">
            {t('settings.title')}
          </h3>
          <button
            onClick={onClose}
            className="text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)]"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        {isLoading ? (
          <div className="flex items-center justify-center py-8">
            <div className="text-[var(--color-text-muted)]">
                {t('common.loading')}
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Skill Settings */}
            <div className="p-4 rounded-lg bg-[var(--color-elevated)]">
              <h4 className="text-md font-medium text-[var(--color-text-primary)] mb-4">
                {t('settings.skill')}
              </h4>

              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-sm text-[var(--color-text-primary)]">
                      {t('settings.autoGenerate')}
                    </div>
                    <div className="text-xs text-[var(--color-text-muted)]">
                      {t('settings.autoGenerateDesc')}
                    </div>
                  </div>
                  <label className="relative inline-flex items-center cursor-pointer">
                    <input
                      type="checkbox"
                      className="sr-only peer"
                      checked={skillSettings.autoGenerate}
                      onChange={(e) => handleAutoGenerateChange(e.target.checked)}
                    />
                    <div className="w-11 h-6 bg-gray-600 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-[var(--color-primary)]"></div>
                  </label>
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-sm text-[var(--color-text-primary)]">
                      {t('settings.triggerThreshold')}
                    </div>
                    <div className="text-xs text-[var(--color-text-muted)]">
                      {t('settings.triggerThresholdDesc')}
                    </div>
                  </div>
                  <input
                    type="number"
                    min="1"
                    max="20"
                    value={localSkillThreshold}
                    onChange={(e) => setLocalSkillThreshold(parseInt(e.target.value) || 1)}
                    onBlur={handleThresholdChange}
                    className="w-16 px-2 py-1 text-center rounded border border-[var(--color-border)] bg-[var(--color-surface)] text-[var(--color-text-primary)] focus:border-[var(--color-primary)] focus:outline-none"
                  />
                </div>
              </div>
            </div>

            {/* Preview Settings */}
            <div className="p-4 rounded-lg bg-[var(--color-elevated)]">
              <h4 className="text-md font-medium text-[var(--color-text-primary)] mb-4">
                {t('settings.preview')}
              </h4>

              <div className="flex items-center justify-between">
                <div>
                  <div className="text-sm text-[var(--color-text-primary)]">
                    {t('settings.fps')}
                  </div>
                  <div className="text-xs text-[var(--color-text-muted)]">1-30 FPS</div>
                </div>
                <input
                  type="number"
                  min="1"
                  max="30"
                  value={localPreviewFps}
                  onChange={(e) => setLocalPreviewFps(parseInt(e.target.value) || 5)}
                  onBlur={handleFpsChange}
                  className="w-16 px-2 py-1 text-center rounded border border-[var(--color-border)] bg-[var(--color-surface)] text-[var(--color-text-primary)] focus:border-[var(--color-primary)] focus:outline-none"
                />
              </div>
            </div>

            {/* About */}
            <div className="p-4 rounded-lg bg-[var(--color-elevated)]">
              <div className="text-sm text-[var(--color-text-muted)]">
                OpenCowork v{(window as any).__APP_VERSION__ || '0.10.9'}
              </div>
              <div className="text-xs text-[var(--color-text-muted)] mt-1">© 2024 OpenCowork</div>
            </div>
          </div>
        )}

        <div className="mt-6 flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-[var(--color-primary)] text-white rounded-md hover:bg-[var(--color-primary-hover)]"
          >
            {t('common.confirm')}
          </button>
        </div>
      </div>
    </div>
  );
}

export default SettingsPanel;
