import React, { useState } from 'react';

export interface SkillCandidateViewModel {
  status: 'generated' | 'suggested';
  skillName?: string;
  description: string;
  actionCount?: number;
  threshold?: number;
  autoGenerated?: boolean;
  source?: string;
  useCases?: string[];
  inputSpec?: string;
  outputSpec?: string;
  failureHints?: string[];
  userInvocable?: boolean;
}

interface SkillCandidateCardProps {
  candidate: SkillCandidateViewModel;
  title?: string;
}

interface SkillSaveEventDetail {
  name: string;
  source: 'agent-created';
}

function slugifySkillName(value: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');

  return slug || 'reusable-workflow';
}

function buildSkillContent(candidate: SkillCandidateViewModel, skillName: string): string {
  const lines: string[] = [
    `# ${skillName}`,
    '',
    candidate.description,
    '',
    '## When to use',
  ];

  if (candidate.useCases && candidate.useCases.length > 0) {
    for (const useCase of candidate.useCases) {
      lines.push(`- ${useCase}`);
    }
  } else {
    lines.push('- Repeatable workflow that can be reused as a skill');
  }

  lines.push('', '## Input');
  lines.push(candidate.inputSpec?.trim() || '- Task description and current context');

  lines.push('', '## Output');
  lines.push(candidate.outputSpec?.trim() || '- A reusable skill draft');

  if (candidate.failureHints && candidate.failureHints.length > 0) {
    lines.push('', '## Failure hints');
    for (const hint of candidate.failureHints) {
      lines.push(`- ${hint}`);
    }
  }

  lines.push(
    '',
    '## Metadata',
    `- Status: ${candidate.status}`,
    `- Action count: ${candidate.actionCount ?? '-'}`,
    `- Threshold: ${candidate.threshold ?? '-'}`,
    `- Auto-generated: ${candidate.autoGenerated ? 'yes' : 'no'}`
  );

  lines.push(`- User invocable: ${candidate.userInvocable === false ? 'no' : 'yes'}`);

  return lines.join('\n');
}

async function saveSkillCandidate(candidate: SkillCandidateViewModel): Promise<{ success: boolean; error?: string }> {
  if (!window.electron) {
    return { success: false, error: 'Electron bridge is unavailable' };
  }

  const defaultName = candidate.skillName || slugifySkillName(candidate.description || 'reusable workflow');
  const inputName = window.prompt('Name this skill', defaultName)?.trim();
  if (!inputName) {
    return { success: false, error: 'Skill name is required' };
  }

  const frontmatter = {
    name: inputName,
    description: candidate.description,
    useCases: candidate.useCases,
    inputSpec: candidate.inputSpec,
    outputSpec: candidate.outputSpec,
    failureHints: candidate.failureHints,
    source: 'agent-created' as const,
    userInvocable: candidate.userInvocable ?? true,
    usageCount: 0,
    version: '1.0.0',
  };

  const content = buildSkillContent(candidate, inputName);
  const result = await window.electron.invoke('skill:save', {
    name: inputName,
    description: candidate.description,
    frontmatter,
    content,
    source: 'agent-created',
  });

  const payload = result?.data || result;
  if (result?.success && payload?.success !== false) {
    window.dispatchEvent(
      new CustomEvent<SkillSaveEventDetail>('skill:changed', {
        detail: { name: inputName, source: 'agent-created' },
      })
    );
    return { success: true };
  }

  return {
    success: false,
    error: payload?.error || result?.error || 'Failed to save skill candidate',
  };
}

function renderChipList(items?: string[]): React.ReactNode {
  if (!items || items.length === 0) {
    return <span className="text-text-muted">-</span>;
  }

  return (
    <div className="flex flex-wrap gap-1.5">
      {items.map((item) => (
        <span key={item} className="rounded bg-border px-2 py-0.5 text-[11px] text-text-secondary">
          {item}
        </span>
      ))}
    </div>
  );
}

export function SkillCandidateCard({ candidate, title = 'Skill candidate' }: SkillCandidateCardProps) {
  const [isSaving, setIsSaving] = useState(false);
  const [saveMessage, setSaveMessage] = useState<string | null>(null);
  const [copyMessage, setCopyMessage] = useState<string | null>(null);

  const handleSave = async () => {
    setIsSaving(true);
    setSaveMessage(null);

    try {
      const result = await saveSkillCandidate(candidate);
      if (result.success) {
        setSaveMessage('Saved as skill');
        window.setTimeout(() => setSaveMessage(null), 2500);
      } else {
        setSaveMessage(result.error || 'Failed to save skill');
      }
    } catch (error) {
      console.error('[SkillCandidateCard] Failed to save candidate:', error);
      setSaveMessage(error instanceof Error ? error.message : 'Failed to save skill');
    } finally {
      setIsSaving(false);
    }
  };

  const handleCopyDraft = async () => {
    try {
      const skillName = candidate.skillName || slugifySkillName(candidate.description || 'reusable workflow');
      const content = buildSkillContent(candidate, skillName);
      await navigator.clipboard.writeText(content);
      setCopyMessage('Draft copied');
      window.setTimeout(() => setCopyMessage(null), 2500);
    } catch (error) {
      console.error('[SkillCandidateCard] Failed to copy draft:', error);
      setCopyMessage(error instanceof Error ? error.message : 'Failed to copy draft');
    }
  };

  return (
    <div className="mt-4 rounded-lg border border-border bg-background px-3 py-3 text-sm text-text-secondary">
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="text-xs uppercase tracking-wide text-text-muted">{title}</div>
          <div className="mt-1 text-white font-medium">{candidate.skillName || 'Reusable workflow candidate'}</div>
        </div>
        <div className="flex items-center gap-2">
          <div className={`rounded px-2 py-1 text-[11px] font-medium ${candidate.status === 'generated' ? 'bg-success/15 text-success' : 'bg-warning/15 text-warning'}`}>
            {candidate.status === 'generated' ? 'Generated' : 'Suggested'}
          </div>
          <button
            type="button"
            onClick={() => void handleCopyDraft()}
            className="rounded bg-border px-2 py-1 text-[11px] font-medium text-white transition-colors hover:bg-border/80"
          >
            Copy Draft
          </button>
          <button
            type="button"
            onClick={() => void handleSave()}
            disabled={isSaving}
            className="rounded bg-primary/15 px-2 py-1 text-[11px] font-medium text-primary transition-colors hover:bg-primary/25 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {isSaving ? 'Saving...' : 'Save as Skill'}
          </button>
        </div>
      </div>
      <div className="mt-2 text-text-secondary">{candidate.description}</div>
      <div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4 text-xs">
        <div>
          <div className="text-text-muted">Action count</div>
          <div className="mt-1 text-white">{candidate.actionCount ?? '-'}</div>
        </div>
        <div>
          <div className="text-text-muted">Threshold</div>
          <div className="mt-1 text-white">{candidate.threshold ?? '-'}</div>
        </div>
        <div>
          <div className="text-text-muted">Generation</div>
          <div className="mt-1 text-white">{candidate.autoGenerated ? 'Auto' : 'Manual review'}</div>
        </div>
        <div>
          <div className="text-text-muted">Source</div>
          <div className="mt-1 text-white">{candidate.source || '-'}</div>
        </div>
        <div>
          <div className="text-text-muted">Invocability</div>
          <div className="mt-1 text-white">
            {candidate.userInvocable === false ? 'Model only' : 'User invocable'}
          </div>
        </div>
      </div>
      <div className="mt-3 grid gap-3 md:grid-cols-2 text-xs">
        <div>
          <div className="text-text-muted mb-1">Use cases</div>
          {renderChipList(candidate.useCases)}
        </div>
        <div>
          <div className="text-text-muted mb-1">Failure hints</div>
          {renderChipList(candidate.failureHints)}
        </div>
        <div>
          <div className="text-text-muted mb-1">Input</div>
          <div className="text-text-secondary whitespace-pre-wrap break-words">
            {candidate.inputSpec || '-'}
          </div>
        </div>
        <div>
          <div className="text-text-muted mb-1">Output</div>
          <div className="text-text-secondary whitespace-pre-wrap break-words">
            {candidate.outputSpec || '-'}
          </div>
        </div>
      </div>
      {saveMessage && <div className="mt-3 text-xs text-text-muted">{saveMessage}</div>}
      {!saveMessage && copyMessage && <div className="mt-3 text-xs text-text-muted">{copyMessage}</div>}
    </div>
  );
}
