import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const setCurrentResult = vi.fn();
const openRunsPanel = vi.fn();
const prepareDraftFromTemplate = vi.fn();
const prepareDraftFromPrompt = vi.fn();
const invoke = vi.fn();
const currentTemplateId = 'template-1';

vi.mock('../../stores/taskStore', () => ({
  useTaskStore: () => ({
    currentResult: {
      id: 'result-1',
      summary: 'Visual fallback completed successfully',
      artifacts: [],
      rawOutput: {
        skillCandidate: {
          status: 'generated',
          skillName: 'daily-report-skill',
          description: 'Auto-generated from a repeatable reporting workflow.',
          actionCount: 6,
          threshold: 5,
          autoGenerated: true,
          source: 'agent-created',
          useCases: ['Daily reporting'],
          inputSpec: 'Task description and current context',
          outputSpec: 'A reusable skill draft',
          failureHints: ['Review the generated steps before broad reuse'],
        },
        visualTrace: [
          {
            source: 'step',
            routeReason: 'The action and selector hint suggest a visually ambiguous interaction',
            fallbackReason: 'Recoverable selector failure',
            approvedActions: [{ type: 'click' }],
            turns: [
              {
                turnId: 'turn-1',
                proposedActions: [{ type: 'click' }, { type: 'type' }],
                executedActions: [{ type: 'click' }, { type: 'type' }],
                finalMessage: 'Search submitted',
                duration: 1200,
              },
            ],
          },
        ],
        taskRouting: {
          executionMode: 'visual',
          routeMode: 'cua',
          reason: 'visual interaction flow',
          explicit: false,
          source: 'chat',
          visualProvider: {
            id: 'responses-computer',
            name: 'Responses Computer',
            score: 92,
            reasons: ['highest completion', 'supports computer tool'],
            adapterMode: 'responses-computer',
          },
        },
      },
      reusable: true,
      completedAt: 1710000000000,
    },
    currentRunId: 'run-1',
    currentTemplateId,
    task: {
      description: 'Search the page visually',
    },
    setCurrentResult,
    openRunsPanel,
  }),
}));

invoke.mockResolvedValue({ success: true, data: {} });

vi.mock('../../stores/schedulerStore', () => ({
  useSchedulerStore: () => ({
    prepareDraftFromTemplate,
    prepareDraftFromPrompt,
  }),
}));

vi.mock('../../i18n/useTranslation', () => ({
  useTranslation: () => ({
    t: (key: string) => key,
  }),
}));

vi.mock('../RelationBadge', () => ({
  default: ({ label, value, onClick }: { label: string; value: string; onClick?: () => void }) =>
    onClick ? (
      <button type="button" onClick={onClick}>{`${label}:${value}`}</button>
    ) : (
      <span>{`${label}:${value}`}</span>
    ),
}));

vi.mock('../ArtifactViewer', () => ({
  default: () => <div>artifact-viewer</div>,
}));

import { ResultPanel } from '../ResultPanel';

describe('ResultPanel', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.spyOn(window, 'dispatchEvent');
    Object.defineProperty(window, 'electron', {
      configurable: true,
      value: { invoke },
    });
  });

  it('renders visual trace summary details from rawOutput', () => {
    render(<ResultPanel />);

    expect(screen.getByText('taskPanels.visualTrace')).toBeInTheDocument();
    expect(
      screen.getByText('The action and selector hint suggest a visually ambiguous interaction')
    ).toBeInTheDocument();
    expect(screen.getByText('Recoverable selector failure')).toBeInTheDocument();
    expect(screen.getByText('click')).toBeInTheDocument();
    expect(screen.getAllByText('click, type').length).toBeGreaterThanOrEqual(2);
    expect(screen.getByText('Search submitted')).toBeInTheDocument();
    expect(screen.getByText('1200ms')).toBeInTheDocument();
    expect(screen.getByText('Responses Computer')).toBeInTheDocument();
    expect(
      screen.getAllByText((_, element) =>
        element?.textContent?.replace(/\s+/g, ' ').trim() === 'score: 92'
      ).length
    ).toBeGreaterThan(0);
    expect(screen.getByText('highest completion')).toBeInTheDocument();
    expect(screen.getByText('Skill candidate')).toBeInTheDocument();
    expect(screen.getByText('daily-report-skill')).toBeInTheDocument();
    expect(screen.getByText('Daily reporting')).toBeInTheDocument();
    expect(screen.getByText('Task description and current context')).toBeInTheDocument();
    expect(screen.getByText('A reusable skill draft')).toBeInTheDocument();
  });

  it('emits template changed when saving a template from a run', async () => {
    render(<ResultPanel />);

    fireEvent.click(screen.getByRole('button', { name: 'taskPanels.saveAsTemplate' }));

    await waitFor(() => {
      expect(invoke).toHaveBeenCalledWith('template:createFromRun', { runId: 'run-1' });
    });

    expect(window.dispatchEvent).toHaveBeenCalledWith(expect.any(CustomEvent));
  });

  it('opens the template panel from the current template badge', () => {
    render(<ResultPanel />);

    fireEvent.click(screen.getByRole('button', { name: 'template:template-1' }));

    expect(window.dispatchEvent).toHaveBeenCalledWith(
      expect.objectContaining({
        type: 'template:open',
        detail: { templateId: 'template-1' },
      })
    );
  });
});
