import { jsx as _jsx } from "react/jsx-runtime";
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { SkillCandidateCard } from '../SkillCandidateCard';
const invoke = vi.fn();
describe('SkillCandidateCard', () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    beforeEach(() => {
        vi.clearAllMocks();
        Object.defineProperty(window, 'electron', {
            value: { invoke },
            configurable: true,
        });
        Object.defineProperty(navigator, 'clipboard', {
            configurable: true,
            value: {
                writeText,
            },
        });
        vi.spyOn(window, 'prompt').mockReturnValue('saved-skill');
        vi.spyOn(window, 'dispatchEvent');
        invoke.mockResolvedValue({ success: true });
    });
    it('saves a skill candidate through skill:save', async () => {
        render(_jsx(SkillCandidateCard, { candidate: {
                status: 'generated',
                skillName: 'daily-report-skill',
                description: 'Auto-generated from a repeatable reporting workflow.',
                actionCount: 6,
                threshold: 5,
                autoGenerated: true,
                source: 'agent-created',
                userInvocable: false,
                useCases: ['Daily reporting'],
                inputSpec: 'Task description and current context',
                outputSpec: 'A reusable skill draft',
                failureHints: ['Review the generated steps before broad reuse'],
            } }));
        fireEvent.click(screen.getByRole('button', { name: 'Save as Skill' }));
        await waitFor(() => {
            expect(invoke).toHaveBeenCalledWith('skill:save', expect.objectContaining({
                name: 'saved-skill',
                description: 'Auto-generated from a repeatable reporting workflow.',
                source: 'agent-created',
                frontmatter: expect.objectContaining({
                    name: 'saved-skill',
                    description: 'Auto-generated from a repeatable reporting workflow.',
                    useCases: ['Daily reporting'],
                    inputSpec: 'Task description and current context',
                    outputSpec: 'A reusable skill draft',
                    failureHints: ['Review the generated steps before broad reuse'],
                    source: 'agent-created',
                    userInvocable: false,
                }),
                content: expect.stringContaining('User invocable: no'),
            }));
        });
        expect(window.dispatchEvent).toHaveBeenCalledWith(expect.any(CustomEvent));
        expect(screen.getByText('Saved as skill')).toBeInTheDocument();
        expect(screen.getByText('Model only')).toBeInTheDocument();
    });
    it('copies the skill draft content', async () => {
        render(_jsx(SkillCandidateCard, { candidate: {
                status: 'generated',
                skillName: 'daily-report-skill',
                description: 'Auto-generated from a repeatable reporting workflow.',
                actionCount: 6,
                threshold: 5,
                autoGenerated: true,
                source: 'agent-created',
                userInvocable: true,
                useCases: ['Daily reporting'],
                inputSpec: 'Task description and current context',
                outputSpec: 'A reusable skill draft',
                failureHints: ['Review the generated steps before broad reuse'],
            } }));
        fireEvent.click(screen.getByRole('button', { name: 'Copy Draft' }));
        await waitFor(() => {
            expect(writeText).toHaveBeenCalledWith(expect.stringContaining('# daily-report-skill'));
        });
    });
});
