export const ERROR_CODES = {
    FEISHU_AUTH_FAILED: 'FEISHU_AUTH_FAILED',
    FEISHU_TOKEN_EXPIRED: 'FEISHU_TOKEN_EXPIRED',
    COMMAND_NOT_RECOGNIZED: 'COMMAND_NOT_RECOGNIZED',
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
    TASK_ALREADY_COMPLETED: 'TASK_ALREADY_COMPLETED',
    IPC_FORWARD_FAILED: 'IPC_FORWARD_FAILED',
    BINDING_NOT_FOUND: 'BINDING_NOT_FOUND',
};
